baseURL = "https://www.lnewby.com/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Lance Newby"
    description = "Lance Newby"

    [params.theme]
        allowToggle = true
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        altTheme = "light"

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Lance Newby"
		tagline = "Designer + Engineer"
		location = "Los Angeles, CA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://linkedin.com/in/lnewby"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/lnewby"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/lancenewby"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I seek to leverage my background in Software Engineering and Graphic Design within a team to (1) serve end-users by exploiting the unique features not yet realized at the intersection of technology and design, and (2) provide enjoyable user experiences that aid in visibility, accessibility, and usability. "

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Game Director for Skyfarer"
            dates = "Mar 2019 - Present"
            company = "USC Games"
            details = "Skyfarer | Mixed Reality Action-Adventure Game for Shoulder Pain Rehabilitation Created by Marientina Gotsis | Executive Producer and Associate Professor of Research at the USC Interactive Media & Games Division"
        [[params.experience.list]]
            position = "Software Engineer"
            dates = "Apr 2013 - Feb 2018"
            company = "Angie's List"
            details = "Development team member responsible for researching and development of design stack and web present for Angie’s List web services."
        [[params.experience.list]]
            position = "Assistant to Director"
            dates = "Jun 2011 - Apr 2013"
            company = "International Center for China Studies - UNC Charlotte"
            details = "Strengthen ties and understanding between China, UNC Charlotte, and the State of North Carolina by exchanging knowledge across academic disciplines, promoting socio-economic interactions and an understanding of Chinese life and culture."
        [[params.experience.list]]
            position = "Director of R&D"
            dates = "Aug 2006 - Dec 2012"
            company = "Failure Free "
            details = "Designer of the web based presence of the company. Responsible for managing a team of 5 people to insure data integrity, accessibility, and visibility of web based solutions."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S. in Computer Science | Game Development"
            college = "University of Sourthern California"
            dates = "2018 - 2020 (expected)"
        [[params.education.list]]
            degree = "B.S. in Computer Science"
            college = "University of North Carolina at Charlotte"
            dates = "2011"
        [[params.education.list]]
            degree = "B.A. in Art | Graphic Design"
            college = "University of North Carolina at Charlotte"
            dates = "2011"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"          

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Javascript, C++, Python"
            skillrating = 75
        [[params.skill.list]]
            skill = "Unreal Engine, Unity, Maya"
            skillrating = 50
        [[params.skill.list]]
            skill = "Illustrator, Photoshop, Gimp"
            skillrating = 70

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Game Design"
        [[params.hobby.list]]		
		    hobby = "Cycling"
        [[params.hobby.list]]		
		    hobby = "Swimming"